### ISSUE TITLE
Auto fill in commands not requested

### ISSUE THREAD

**Issue by bovirus** [katahiromz/RisohEditor#101]
@katahiromz 

Editing astructure like

LANGUAGE LANG_ITALIAN, SUBLANG_DEFAULT

1035 DIALOGEX 0, 0, 328, 238
CAPTION "Ridimensiona/ricampiona immagine"
STYLE DS_CENTER | DS_SETFOREGROUND | DS_MODALFRAME | WS_POPUPWINDOW | WS_CAPTION | WS_VISIBLE
FONT 8, "Microsoft Sans Serif", 0, 0, 0
{
    EDITTEXT 1859, 43, 60, 31, 12, WS_GROUP
    EDITTEXT 1857, 112, 60, 31, 12, WS_GROUP
    AUTORADIOBUTTON "pixel", 1815, 36, 77, 34, 9, WS_GROUP | WS_TABSTOP
    AUTORADIOBUTTON "cm", 1808, 70, 77, 25, 9, WS_TABSTOP
    AUTORADIOBUTTON "pollici", 1814, 96, 77, 35, 9, WS_TABSTOP
    EDITTEXT 1796, 43, 111, 31, 12, WS_GROUP
    EDITTEXT 1795, 116, 110, 31, 12, WS_GROUP
    AUTORADIOBUTTON "Impo&sta nuova dimensione:", 1851, 9, 46, 108, 11, WS_GROUP | WS_TABSTOP, WS_EX_TRANSPARENT
    AUTORADIOBUTTON "Imposta dime&nsione in % dell'originale:", 1850, 9, 93, 135, 11, WS_TABSTOP, WS_EX_TRANSPARENT
    AUTOCHECKBOX "M&antieni le proporzioni", 1518, 9, 149, 126, 10, WS_GROUP | **_NOT WS_TABSTOP_**
    AUTOCHECKBOX "Aumenta nitidezza dopo i&l ricampionamento", 1519, 9, 162, 151, 10, WS_GROUP | **_NOT WS_TABSTOP_**
    AUTOCHECKBOX "Regola DPI base a nuova dim.(rapp.aspetto)", 1520, 9, 175, 151, 10, WS_DISABLED | **_NOT WS_TABSTOP_**
    LTEXT "DP&I:", -1, 9, 191, 15, 8
    EDITTEXT 1849, 36, 189, 31, 12, ES_NUMBER | WS_GROUP
    GROUPBOX "Di&mensione immagine (in pixel):", -1, 166, 0, 159, 137
    COMBOBOX 1860, 172, 12, 69, 237, CBS_HASSTRINGS | CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP
    AUTORADIOBUTTON "&640 x 480", 1844, 172, 30, 60, 11, WS_GROUP | WS_TABSTOP
    AUTORADIOBUTTON "&800 x 600", 1845, 172, 43, 60, 11, NOT WS_TABSTOP
    AUTORADIOBUTTON "&1024 x 768", 1846, 172, 56, 60, 11, NOT WS_TABSTOP
    AUTORADIOBUTTON "1&280 x 720   (HD)", 1863, 249, 30, 74, 11, NOT WS_TABSTOP
    AUTORADIOBUTTON "1&920 x 1080 (FHD)", 1848, 249, 43, 74, 11, NOT WS_TABSTOP
    AUTORADIOBUTTON "38&40 x 2160 (4K)", 1865, 249, 56, 74, 11, NOT WS_TABSTOP
    AUTORADIOBUTTON "&7680 x 4320 (8K)", 1866, 249, 69, 74, 11, NOT WS_TABSTOP
    AUTORADIOBUTTON "Adatta a schermo", 1853, 172, 69, 66, 11, NOT WS_TABSTOP
    AUTORADIOBUTTON "&Dimensioni schermo (non proporzionale)", 1852, 172, 82, 140, 11, NOT WS_TABSTOP
    PUSHBUTTON "Di&mezza", 1856, 172, 97, 69, 14
    PUSHBUTTON "Ra&ddoppia", 1855, 249, 97, 69, 14
    AUTORADIOBUTTON "&Ricampiona (qualità migliore), usa filtro:", 1988, 172, 149, 134, 10, WS_GROUP | WS_TABSTOP
    AUTORADIOBUTTON "Ridim&ensiona (più veloce, qualità peggiore)", 1989, 172, 176, 149, 10, NOT WS_TABSTOP
    COMBOBOX 1843, 184, 160, 138, 81, CBS_HASSTRINGS | CBS_DROPDOWNLIST | WS_VSCROLL | WS_TABSTOP
    DEFPUSHBUTTON "&OK", IDOK, 87, 221, 69, 14
    PUSHBUTTON "&Annulla", IDCANCEL, 172, 221, 69, 14
    LTEXT "Larghezza:", -1, 6, 113, 36, 8
    GROUPBOX "", -1, 3, 47, 159, 44
    LTEXT "Larghezza:", -1, 6, 62, 37, 8
    LTEXT "Altezza:", -1, 86, 62, 23, 8
    LTEXT "Dimensione attuale:", 1854, 9, 10, 143, 10
    GROUPBOX "", -1, 3, 94, 159, 43
    LTEXT "%  Altezza:", -1, 77, 113, 36, 8
    LTEXT "%", -1, 150, 113, 8, 9
    GROUPBOX "", -1, 3, 0, 159, 44
    GROUPBOX "Metodo ridimensionamento:", -1, 166, 139, 159, 79
    GROUPBOX "", -1, 3, 139, 159, 79
    LTEXT "Unità:", -1, 12, 77, 19, 8
    LTEXT "Nuova dimensione:", 1858, 9, 26, 143, 10
    LTEXT "(mantieni rapporto)", -1, 245, 14, 66, 8
    LTEXT "(automatico per cm/pollici)", -1, 72, 191, 100, 8
    PUSHBUTTON "S&cambia i lati", 1861, 172, 117, 69, 14
    PUSHBUTTON "Aggiungi ai comuni", 1862, 249, 117, 69, 14
    AUTOCHECKBOX "Filtro ricampiona veloce per ridimensiona", 3274, 172, 192, 147, 10
    AUTOCHECKBOX "Migliora gamma per ricampionamento", 1983, 172, 205, 146, 10
    GROUPBOX "", -1, 166, 184, 159, 34
	
The original source not include the text in bold italic.
I tried to delete the trxt in bold when I recompile with icon in RisohEditor I found again thr bold trxt.

What's about?

**Comment by katahiromz** [comment]
That's the bug of resource compiler `windres`.
The default style of `AUTOCHECKBOX` must have `WS_TABSTOP` style.

**Comment by katahiromz** [comment]
I have reported it to sourceware.
https://sourceware.org/bugzilla/show_bug.cgi?id=26340

**Comment by katahiromz** [comment]
That's a bug of resource compiler `windres`.
I have reported to sourceware:
https://sourceware.org/bugzilla/show_bug.cgi?id=26340

**Comment by katahiromz** [comment]
The patch is committed: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=37f628c34d2d1f7e30c95b21f9c4c21819cb4534

Have a wait for the next release of binutils...

**Comment by katahiromz** [comment]
Confirmed FIXED. Thanks!
