### ISSUE TITLE
"GUI Edit" and "Test" command - Different view

### ISSUE THREAD

**Issue by bovirus** [katahiromz/RisohEditor#104]
Probably I found an issue.

Using RisohEditor 5.4.5 and open the dll attached (inside teh zip) I check that only for 

[Italian2.zip](https://github.com/katahiromz/RisohEditor/files/5042417/Italian2.zip)

RT_Dialog -> 1009

If you open with GUI Edit yiou full GUI image (it's OK)

![image](https://user-images.githubusercontent.com/1262554/89664234-1fb8e280-d8d7-11ea-85c2-85f4af4c8151.png)

If you use "Test" you get a strange view.

![image](https://user-images.githubusercontent.com/1262554/89664275-32cbb280-d8d7-11ea-966d-05830e8c78a3.png)

Could you please check?

**Comment by katahiromz** [comment]
Confirmed.
