### ISSUE TITLE
Command Line Support for Exporting .rc/.res

### ISSUE THREAD

**Issue by SaifRushdHadad** [katahiromz/RisohEditor#133]
Currently RisohEditor does not support command line invocation (besides taking the first argument provided and loading it). Would it be possible to implement flag and argument support so RisohEditor could be used without a GUI? Being able to export `.rc` and `.res` files quickly would be very useful to a lot of users.

**Comment by katahiromz** [comment]
1. Extend command line syntax:
- `/?` or `--help`: Show usage.
- `--version`: Show version info.
- `--execute "your_file.ega"`: Execute an EGA script.

2. Extend the EGA language:
- Add `RES_load` function (Load resource file).
- Add `RES_save` function (Save resource file).
- Add `RES_close` function (Close the window).

**Comment by katahiromz** [comment]
`RES_load(filename)`
`RES_save(filename, options...)`
`RES_close()`

`RES_load` and `RES_save` will use the filename extension.

`RES_save` options:
- `"separate"`: Separate resource files by language.
- `"begin-end"`: Use `BEGIN`/`END`.
- `"lang-macro"`: Make language selectable by `LANGUAGE_*` macro.
- `"backup"`: Make backup.
- `"add-comments"`: Output redundant comments.
- `"wrap-manifest"`: Wrap the manifest statements by `#ifndef MSVC ... #endif`.
- `"utf-16"`: Output RC files as UTF-16.

**Comment by katahiromz** [comment]
- Add no-gui mode.
- Virtualize message box.

**Comment by katahiromz** [comment]
![image](https://user-images.githubusercontent.com/2107452/122578124-89c11d00-d08e-11eb-97f5-a62a5f13af6c.png)
