### ISSUE TITLE
Readme suggestion:  Loading System32 64-bit files

### ISSUE THREAD

**Issue by dxgldotorg** [katahiromz/RisohEditor#156]
According to https://docs.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector on Windows Vista and greater you can still access 64-bit executables stored in System32 by going to the hidden, virtual folder sysnative in the Windows folder.

Program Files is not redirected but instead is set to Program Files (x86) via environment variable for 32-bit applications.  The file picker can still read 64-bit Program Files just fine.

**Comment by katahiromz** [comment]
We can disable the redirection by `Wow64DisableWow64FsRedirection` and revert the redirection by `Wow64RevertWow64FsRedirection`.

Okay, I will try it.

**Comment by katahiromz** [comment]
`32-bit OpenFileDialog --> 64-bit System32?`
https://stackoverflow.com/questions/5241451/32-bit-openfiledialog-64-bit-system32

> I believe that this is simply not possible.

**Comment by katahiromz** [comment]
Won't fix. Sorry.
