### ISSUE TITLE
I want the translator's name to be displayed.

### ISSUE THREAD

**Issue by VenusGirl** [katahiromz/RisohEditor#178]
I hope the name of the translator will be displayed on the program information display.

![번역자](https://user-images.githubusercontent.com/53147200/159131224-e7699aa3-e469-438b-a4b8-3fa83e4a37b6.png)

**Comment by katahiromz** [comment]
Added:
https://github.com/katahiromz/RisohEditor/commit/b2b2c445cad87c03163eee6ff4c62873eef8ac4e

2022年3月20日(日) 2:18 VenusGirl❤ ***@***.***>:
