### ISSUE TITLE
Request to add Korean to the installer.

### ISSUE THREAD

**Issue by VenusGirl** [katahiromz/RisohEditor#208]
Request to add Korean to the installer.

The Inno setup Korean installation script can be downloaded here.
https://github.com/jrsoftware/issrc/blob/main/Files/Languages/Unofficial/Korean.isl

or  [INNO Setup - Korean.zip](https://github.com/katahiromz/RisohEditor/files/11140159/INNO.Setup.-.Korean.zip)

**Comment by katahiromz** [comment]
I need Inno Setup 5.6.1 (u) to support Windows XP.
The Korean translation file you provided is for Inno Setup 6.1.0+.

**Comment by VenusGirl** [comment]
Inno Setup 5 Final Version
[INNO Setup - Korean5.zip](https://github.com/katahiromz/RisohEditor/files/11149002/INNO.Setup.-.Korean5.zip)

**Comment by katahiromz** [comment]
Is it under GPL-3 License?

**Comment by katahiromz** [comment]
![image](https://user-images.githubusercontent.com/2107452/229811469-3ee6045f-53a0-4232-b825-e19fc5e995c6.png)
There were some warnings from Inno Setup.

**Comment by katahiromz** [comment]
![image](https://user-images.githubusercontent.com/2107452/229812577-9fb93317-7f31-4db2-af5a-de6e35b8fff3.png)

**Comment by VenusGirl** [comment]
Okay, good.

**Comment by katahiromz** [comment]
See https://github.com/katahiromz/RisohEditor/commit/1a7924617cd617c1f3b6c7a9ec246b9f622c408e
