### ISSUE TITLE
Incorrect separators in MENUEX

### ISSUE THREAD

**Issue by vanjac** [katahiromz/RisohEditor#211]
When a menu is set to Extended type, RisohEditor still writes menu separators as:
`MENUITEM SEPARATOR`

but this will fail to compile with RC. For MENUEX menus items must use `MFT_SEPARATOR` instead of `SEPARATOR`.

**Comment by katahiromz** [comment]
Thanks for reporting. I will try to fix it later.

**Comment by katahiromz** [comment]
![image](https://user-images.githubusercontent.com/2107452/236774828-2cae137f-7455-4ae2-bffe-9cc910bcf5e7.png)
