### ISSUE TITLE
Ошибка компиляции

### ISSUE THREAD

**Issue by UnrealKaraulov** [katahiromz/RisohEditor#231]
---------------------------
RisohEditor 5.7.8 (c) Katayama Hirofumi MZ
---------------------------
Ошибка компиляции.
---------------------------
ОК   
---------------------------

![image](https://github.com/katahiromz/RisohEditor/assets/88730285/5cd3e36e-a2e5-4718-bc7e-7c869b64e38d)

**Comment by UnrealKaraulov** [comment]
Even if create default version resource. (

**Comment by katahiromz** [comment]
Could you please paste the text data that the compilation error happens?

**Comment by katahiromz** [comment]
The header file `resource.h` if any, too.

**Comment by katahiromz** [comment]
Incomplete description.
Closed.
