### ISSUE TITLE
Not able to open up input file

### ISSUE THREAD

**Issue by greenozon** [katahiromz/RisohEditor#234]
the tool is eating 1 CPU core 100% and RAM is slowly increasing, the app is not responsive for long time

![image](https://github.com/katahiromz/RisohEditor/assets/765343/59d9c72b-782a-4e91-9c56-eae0a6563e79)

input file attached
[bin20K.zip](https://github.com/katahiromz/RisohEditor/files/13801084/bin20K.zip)

Tool used:  version 5.7.9 portable

**Comment by katahiromz** [comment]
Virus detected. Sorry, no thanks.

**Comment by greenozon** [comment]
this binary is created by myself, if you wish I could attach MASM based project
this project was a spinoff of some QA related activities on another big project...

what virus have you seen in this binary??
I'm just very very curious

here is a AV scan result: https://www.virustotal.com/gui/file/4ea70599c0a5500bca80921d97727cf47fc7d713730709c7027eba54ada283c8?nocache=1

**Comment by katahiromz** [comment]
You have enough knowledge to debug this issue. I don't want to help you.

**Comment by greenozon** [comment]
Thank you, @katahiromz -san
I'll come back when have news
