### ISSUE TITLE
Hex-Editor MX - Export Failed

### ISSUE THREAD

**Issue by FunkyFr3sh** [katahiromz/RisohEditor#240]
I get "Export Failed" when trying to to "File->Export..." on a old hex editor named "Hex-Editor MX"

You should find it on google, but I can also attach the .exe here if needed

**Comment by katahiromz** [comment]
This issue is related to Wow64.
If you move the program from `C:\Program Files\HxD\HxD.exe`, then you can export.
Closed.

**Comment by FunkyFr3sh** [comment]
it's not HxD, it's Hex-Editor MX

![image](https://github.com/user-attachments/assets/5f121838-5577-4e1d-91a4-3d2af039d7c4)

**Comment by katahiromz** [comment]
The resource data of this EXE file is compressed with unknown format.
We cannot decode this type compression.
Closed.
