### ISSUE TITLE
RisohEditor 5.1.5 - Feedbacks about GUI (untranslated strings)

### ISSUE THREAD

**Issue by bovirus** [katahiromz/RisohEditor#43]
There are some screens with text untranslated
And some parts that could be a slight impovemnts of GUI design.

Please check the screenshots.

![risoheditor-5 1 5-gui-01](https://user-images.githubusercontent.com/1262554/53001582-4822f780-342b-11e9-80be-62f6098bdf09.jpg)
![risoheditor-5 1 5-gui-02](https://user-images.githubusercontent.com/1262554/53001558-380b1800-342b-11e9-8be7-1299d7d3a5bf.jpg)
![risoheditor-5 1 5-gui-03](https://user-images.githubusercontent.com/1262554/53001568-3f322600-342b-11e9-8d3f-2162713c434f.jpg)

Thanks.

**Comment by katahiromz** [comment]
Please retest.

**Comment by bovirus** [comment]
Have you download again the program and test again?

**Comment by katahiromz** [comment]
Can you pull the source and build it?

**Comment by bovirus** [comment]
Sorry. I cannot build it.
Please build and make available a temporary download to test it.

**Comment by katahiromz** [comment]
https://github.com/katahiromz/downloads

**Comment by bovirus** [comment]
OK. Quite nice.
Untranslated strings now are OK.
Word Wrap now is ok (not truncated).
Please check 3rd screenshot.

"Create backup" text string should be moved a few on the left (too space empty after the checkbox) near to checkbox.
"backup suffix" should be moved on the right near to drop down control.

**Comment by katahiromz** [comment]
Updated.
https://github.com/katahiromz/downloads

**Comment by bovirus** [comment]
Ok. Thanks. Fixed.
Found untranslated string
In "Predefined Macros" window the "Edit" button is untranslated.

The Open/Save dialog box (and generally any window that requitre open/save function) could be ridesigned using better the GUI space.
Please check the two screenshot of current and my propsoal changes.

![risoheditor-5 1 5-gui-04a](https://user-images.githubusercontent.com/1262554/53007584-d56c4900-3437-11e9-9aef-5dd4648096f2.jpg)

![risoheditor-5 1 5-gui-04b](https://user-images.githubusercontent.com/1262554/53007598-dbfac080-3437-11e9-91cf-041a6592be40.jpg)

Move File name and nae box on the left (usinge empty space on teh left)
Decrease a little the file name box
Increase the file type control width
Move OK/Cancel buttons centered on the window width.

**Comment by katahiromz** [comment]
I don't know how to fix Open/Save dialog.

**Comment by bovirus** [comment]
@katahiromz 

Please identify if you have a module that you can handle the position of file name string/file name box/file type drop down list and Open/Cancel buttons.

Please rebuild the installer/zip file using my latest version of Italian language.

**Comment by katahiromz** [comment]
Those are Common Dialogs. I don't know how to edit Common Dialog.

**Comment by bovirus** [comment]
What's your development system to create the application?

Please rebuild the application with latest Italian language file.

**Comment by katahiromz** [comment]
Uploaded new.
https://github.com/katahiromz/downloads
You can watch this downloads site.

**Comment by katahiromz** [comment]
My build system is MSYS2.

**Comment by bovirus** [comment]
Small update about Italian language ("Edit" -> "Modifica").
I forgot to revise it. Sorry.
Please rebuild the installer.

I will check if and how to revise MSYS2 common dialog.

**Comment by katahiromz** [comment]
Common Dialogs are in Win32 API. Not in MSYS2.

**Comment by bovirus** [comment]
Info about customizing standard window controls

https://docs.microsoft.com/en-us/windows/desktop/dlgbox/customizing-common-dialog-boxes

**Comment by katahiromz** [comment]
I don't do it. Sorry.
