### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MeatPony** [katahiromz/RisohEditor#67]

**Comment by MeatPony** [comment]
oops

**Comment by MeatPony** [comment]
didnt mean to post

**Comment by MeatPony** [comment]
how do i delete

**Comment by MeatPony** [comment]
i accidentally hit enter, and it posted the issue

**Comment by MeatPony** [comment]
Well, I'll just continue what I was going to say here

I found a gameboy emulator, that is partially in japanese, I wanted to translate it to english, so i wanted to start with the about dialog, i attempted to load it in risoheditor and it worked, but when i tried to edit the dialog it only showed the dialog with no text inside, i looked around everywhere inside of the risoheditor and could not find a trace of the string that went in that dialog.
![image](https://user-images.githubusercontent.com/58016720/80402489-f924ed80-888b-11ea-91f5-7506806ac981.png)

**Comment by MeatPony** [comment]
![image](https://user-images.githubusercontent.com/58016720/80402571-13f76200-888c-11ea-854b-7b480e9e4e83.png)
here is what it should normally look like (Those garbled characters are likely japanese, but I do not have all the proper fonts installed, so they dont display properly.

**Comment by katahiromz** [comment]
Where did you download from?

**Comment by MeatPony** [comment]
A friend sent it to me over discord

**Comment by katahiromz** [comment]
I cannot test it. Closed.
